### ISSUE TITLE
npm上的版本不是最新的

### ISSUE THREAD

**Issue by xdoer** [JS-Hao/audio-sculptor#1]
作者你好，你npm上的包中的代码和你仓库中的代码不一致。导致你demo中的代码没办法运行。
如图是npm仓库和github的代码打印实例的对比图
![image](https://user-images.githubusercontent.com/22864183/66458782-294e9f80-eaa6-11e9-800b-12a4535cb276.png)
![image](https://user-images.githubusercontent.com/22864183/66458811-408d8d00-eaa6-11e9-99e0-c82a2e6536e0.png)

**Comment by JS-Hao** [comment]
谢谢你的反馈，已发最新的npm包，并将demo的代码进行了调整，直接npm run start即可

**Comment by JS-Hao** [comment]
https://github.com/JS-Hao/audio-sculptor/commit/d87b1fc917a49d8143b8acf08e2c211e163d9c7f
