### ISSUE TITLE
关于Ffmpeg worker mp4 

### ISSUE THREAD

**Issue by ZYMoridae** [JS-Hao/audio-sculptor#10]
请问ffmpeg-worker-mp4.js是官方的那个版本还是自己编译的？如果是自己编译的是否有差别呢？

**Comment by JS-Hao** [comment]
来源于此仓库 https://github.com/Kagami/ffmpeg.js  官方仅提供的是 ffmpeg，此仓库的作者自己编成了 js 版本

**Comment by ZYMoridae** [comment]
如果我用官方的npm的module只有10MB，我看和此库使用的ffmpeg-worker-mp4.js有体积差别，不知作者是否进行了优化。

**Comment by JS-Hao** [comment]
你指的10MB具体是指哪个仓库下的module? 能否提供链接呢？

**Comment by ZYMoridae** [comment]
使用npm安装ffmpeg.js后在node_module里面可以找到ffmpeg-worker-mp4.js

**Comment by JS-Hao** [comment]
我所使用的是较早的版本，体积稍微偏大，作者在5个月前有更新，猜测应该是重新编译了新版 ffmpeg，并精简了部分ffmpeg模块

PS：此仓库链接并非是FFmpeg官方，官方地址为 [https://ffmpeg.org/](https://ffmpeg.org/)，是用 c 编写的，只是此作者将其改成了js的实现方式

**Comment by ZYMoridae** [comment]
所以说你项目里使用的ffmpeg-worker-mp4.js是通过ffmpeg官方库编译得到的并非是ffmpeg.js所提供的那个worker。

**Comment by ZYMoridae** [comment]
如果我替换成了最新版本的ffmpeg-worker-mp4.js发现同样文件执行同样指令速度也不太一样
