### ISSUE TITLE
将demo中的代码放到自己项目内，并没法真正裁剪，报了以下错误

### ISSUE THREAD

**Issue by MrRetro** [JS-Hao/audio-sculptor#4]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided."

**Comment by JS-Hao** [comment]
你好，由于 sdk 更新后未及时同步文档与 demo 示例，导致此问题发生。现已更新 API 文档及 demo 示例，此问题已解决
