### ISSUE TITLE
audio转换blob功能

### ISSUE THREAD

**Issue by MinggengSun** [JS-Hao/audio-sculptor#7]
大佬，将audio转换成blob之后就没有往下执行了。这是为何？
async main(){
      const audioSculptor = new AudioSculptor();
      console.log(audioSculptor)
      await audioSculptor.open({
            workerPath:'/utils/ffmpeg-worker-mp4.js',
           mediaType:'mp3'
       })

      const audio = new Audio(this.voiceUrl);
      const blob = await audioSculptor.toBlob(audio);
      console.log("往下执行")
      console.log(blob)
}

**Comment by JS-Hao** [comment]
能否捕获到详细报错信息？

**Comment by MinggengSun** [comment]
**Cannot read property 'content-type' of undefined**

return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
                switch (_context3.prev = _context3.next) {
                          case 0:
                          arrayBuffer = res.data;
                          // **contentType = res.headers['content-type'];**  //未定义属性
                                  file = new File([arrayBuffer], 'result', {
                                         type: contentType
                                  });
                                   return _context3.abrupt("return", file);
                }
}, _callee3);

通过audioSculptor.toAudio转换后地址怎么还是blob?

**Comment by JS-Hao** [comment]
需要检查下这个音频链接，它在内部是通过axios去重新拉取该音频的流数据，从而转成blob的，该报错提示没有响应头
